### ISSUE TITLE
Processus de recherche

### ISSUE THREAD

**Issue by Thebaide** [yoannsculo/emploi#32]
Bonjour,

J'aurais voulu savoir les moyens que vous avez utilisé pour établir cette liste ?

**Comment by yoannsculo** [comment]
Bonjour,

Je récupère les noms de sociétés à plein d'endroits

- sur les sites d'actualité spécialisés (exemple : https://www.lembarque.com)
- tous les ans suite au CES de Las Vegas avec les nouvelles startups présentes. Surtout avec la médiatisation autour de la "French Tech"
- les exposants de salons spécialisés (ex. Enova)
- les sites d'offres d'emplois
- en observant autour de moi les noms indiqués sur tout ce qui est électronique dans la rue, les transports, etc.
- via mon réseau professionnel quand on me parle de nouvelles sociétés
- via les réseaux sociaux
- via les prix décernés à des sociétés pour leurs innovations
- en consultant la liste des participants à des Meetups / conférences / salons
- en consultant les listes de CCI
- par hasard en me baladant avec Street View dans des zones industrielles lorsque je cherche l'emplacement précis d'une société. Il m'arrive souvent de découvrir plusieurs sociétés de cette façon en regardant les façades et mêmes les panneaux d'entrée de zone industrielle qui les liste toutes.

Une fois que j'ai le nom, je cherche l'adresse postale sur le site web de la société. Si la société ne l'indique pas, ce qui est très courant, je vais sur societe.com la chercher. Ensuite avec osm.org j'utilise le marqueur de partage (que je déplace à l'endroit de la société) pour récupérer les coordonnées GPS dans l'url que je rajoute dans le .json

**Comment by Thebaide** [comment]
Merci. En tout cas c'est du super taf. Les coordonnées GPS sont bien utiles.
